server:
  port: 8080

spring:
  application:
    name: S05T02

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/VirtualPetWebApplication_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres1234}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:validate}
    show-sql: true
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    placeholders:
      adminEmail: ${APP_ADMIN_EMAIL}
      adminPasswordHash: ${APP_ADMIN_PASSWORD_HASH}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

security:
  jwt:
    secret: ${JWT_SECRET:change-me-dev-secret-64chars}
    user:
      generator: ${JWT_ISSUER:AUTH0JWT-BACKEND}
    exp-minutes: ${JWT_EXP_MINUTES:30}

springdoc:
  swagger-ui:
    path: /swagger-ui
    operationsSorter: alpha
    tagsSorter: alpha
---
spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    cat.itacademy.s05.t02: INFO
    org.springframework.security: INFO
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{36} - %msg%n"

