ALTER TABLE pets
    ADD COLUMN IF NOT EXISTS stamina INTEGER NOT NULL DEFAULT 70,
    ADD COLUMN IF NOT EXISTS level INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS xp_in_level INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS stage VARCHAR(10) NOT NULL DEFAULT 'BABY';


UPDATE pets SET hunger = COALESCE(hunger, 30);
UPDATE pets SET happiness = COALESCE(happiness, 60);